In [1]:
w1, w2, w3 = 0.3, 0.2, 0.5

In [2]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

In [3]:
kanto_yield_apples = kanto_temp * w1 + kanto_rainfall * w2 + kanto_humidity * w3

In [4]:
kanto_yield_apples

56.8

In [5]:
print("The expected yield of apples in Kanto region in {} tons per hectare.".format(kanto_yield_apples))

The expected yield of apples in Kanto region in 56.8 tons per hectare.


In [6]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [7]:
weights = [w1,w2,w3]

In [10]:
def crop_yield(region, weights):
    result = 0
    for x,w in zip(region, weights):
        result += x*w
    return result

In [11]:
crop_yield(kanto, weights)

56.8

In [12]:
crop_yield(johto, weights)

76.9

In [13]:
crop_yield(hoenn, weights)

81.9

In [14]:
crop_yield(unova, weights)

74.9

In [15]:
crop_yield(sinnoh, weights)

57.699999999999996

In [16]:
import numpy as np

In [17]:
kanto = np.array([73,67,43])

In [18]:
kanto

array([73, 67, 43])

In [19]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

In [20]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [24]:
weights = np.array([0.3,0.2,0.5])

In [25]:
weights.shape

(3,)

In [26]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [27]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [28]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])